console.log('is navbar fixed, no. wait, maybe yes. actually, no. SCRUM-1. again')
console.log("scrum 1 again")
console.log("commit without name")
console.log("with name")
console.log("branch name no SCRUM-1")
console.log("navbar")
console.log("jasldkfjs")